# Generated by Django 4.2.14 on 2024-08-25 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='prevBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterusage', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('readDate', models.DateField(default=datetime.date.today)),
                ('dueDate', models.DateField(default=datetime.date.today)),
                ('sanitaryCharge', models.IntegerField()),
                ('meterCharge', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('waterValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currentDue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxName', models.CharField(default='', max_length=50)),
                ('meterFee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sanitaryCharges', models.IntegerField()),
                ('duesInterest', models.IntegerField()),
                ('otherCharges', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='waterCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessOrMore', models.CharField(default='', max_length=40)),
                ('lessThanLiters', models.IntegerField()),
                ('priceFOrLiters', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
